arb-dir: lib/app/l10n
template-arb-file: lang_en.arb
output-localization-file: app_localizations.dart
synthetic-package: false 
# https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization#configuring-the-l10nyaml-file