name: flutter_boilerplate
description: A boilerplate for Flutter.

# SDK version 3.16.0

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #* config
  flutter_dotenv: ^5.1.0
  flutter_flavor: ^3.1.3

  #* di
  get_it: ^7.6.6
  injectable: ^2.3.2  

  #* asset helper
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  flutter_gen: ^5.3.2

  #* localization & converters
  flutter_localizations:
    sdk: flutter
  intl: any

  #* network
  dio: ^5.3.4
  dio_intercept_to_curl: ^0.2.0
  pretty_dio_logger: ^1.3.1
  retrofit: '>=4.0.0 <5.0.0'

  #* network for if we have a swagger documentation
  chopper: ^6.1.1
  json_annotation: ^4.8.0
  pretty_chopper_logger: ^1.0.6

  #* database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  #* firebase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.8.0

  #* navigation
  auto_route: ^7.8.4

  #* utils
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  collection: ^1.18.0
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  device_info_plus: ^9.1.1
  flutter_local_notifications: ^16.3.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter

  build_runner: any
  flutter_gen_runner: any
  retrofit_generator: '>=7.0.0 <8.0.0'
  chopper_generator: ^6.0.0
  json_serializable: ^6.6.1
  swagger_dart_code_generator: ^2.10.4
  isar_generator: ^3.1.0+1
  injectable_generator: ^2.4.1
  auto_route_generator: ^7.3.2

flutter_gen:
  output: lib/app/core/helpers # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/env/
    - assets/env/prod.env
    - assets/env/dev.env
    - assets/icons/
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
